/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ScarCoin__factory } from "./ScarCoin__factory";
export { ScarIndexOracle__factory } from "./ScarIndexOracle__factory";
